Algoritmo "semnome"

Var
hora : inteiro




Inicio
//hora <- 5

escreva("Digite uma hora do dia: ")
leia(hora)
          //PRIMEIRO EXEMPLO DE CONDIÇÃO
//se hora < 12 entao
//   escreval("Bom dia!")
//senao
//   escreval("Boa tarde!")
//fimse

//se hora < 0 entao
//escreval("Boa noite!")
//fimse

se hora < 12 entao
   escreval("Bom dia!")
fimse

se (hora >= 12) e (hora < 18) entao
   escreval("Boa tarde!")
fimse

se hora >= 18 entao
   escreval("Boa noite!")
fimse


Fimalgoritmo